force-app/scenario 2 - flow/objects/Account/fields/Payor_History__c.field-meta.xml
<CustomField>
    <fullName>Payor_History__c</fullName>
    <description>Picklist using the global value set &quot;Payor History.&quot;</description>
    <inlineHelpText>The rating assigned to the Account based on payment history</inlineHelpText>
    <label>Payor History</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payor_History</valueSetName>
    </valueSet>
</CustomField>

force-app/scenario 1 - formula field/objects/Opportunity/fields/Good_Payer_Discount__c.field-meta.xml
<CustomField>
    <fullName>Good_Payer_Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>A calculated value based on the account&#39;s payor history field. Updated via Flow.</description>
    <inlineHelpText>A discount that can be applied due to the Account payment history.</inlineHelpText>
    <label>Good Payer Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/scenario 2 - flow/objects/Payor_History_Discounts__mdt/Payor_History_Discounts__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for assigning discounts for payment history</description>
    <label>Payor History Discount</label>
    <pluralLabel>Payor History Discounts</pluralLabel>
</CustomObject>

force-app/scenario 2 - flow/objects/Payor_History_Discounts__mdt/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Percentage discount to apply for that rating</description>
    <inlineHelpText>The discount to apply</inlineHelpText>
    <label>Discount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/scenario 2 - flow/globalValueSets/Payor_History.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Excellent</fullName>
    </customValue>
    <customValue>
        <fullName>Good</fullName>
    </customValue>
    <customValue>
        <fullName>Average</fullName>
        <default>true</default>
        <label>Average</label>
    </customValue>
    <description>Payor history picklist set used in Account and Opportunities</description>
    <masterLabel>Payor History</masterLabel>
</GlobalValueSet>

force-app/scenario 2 - flow/tests/PayorRatingFlowTests.cls
@isTest
private class PayorRatingFlowTests {

    @isTest static void testNewOpp_Excellent() {
        // arrange
        Double expected = [SELECT Discount__c FROM Payor_History_Discounts__mdt WHERE DeveloperName = 'Excellent'].Discount__c;

        Account a = new Account (
            Name = 'testacct',
            Payor_History__c = 'Excellent'
        );
        insert a;

        Opportunity opp = new Opportunity (
            StageName = 'New',
            AccountId = a.Id,
            CloseDate = Date.today(),
            Name = 'testopp'
        );

        // act
        insert opp;

        // assert
        Opportunity result = [SELECT Good_Payer_Discount__c FROM Opportunity WHERE Id = :opp.Id];

        System.assertEquals(expected, result.Good_Payer_Discount__c);
    }

    @isTest static void testNewOpp_Good() {
        // arrange
        Double expected = [SELECT Discount__c FROM Payor_History_Discounts__mdt WHERE DeveloperName = 'Default'].Discount__c;

        Account a = new Account (
            Name = 'testacct',
            Payor_History__c = 'Good'
        );
        insert a;

        Opportunity opp = new Opportunity (
            StageName = 'New',
            AccountId = a.Id,
            CloseDate = Date.today(),
            Name = 'testopp'
        );

        // act
        insert opp;

        // assert
        Opportunity result = [SELECT Good_Payer_Discount__c FROM Opportunity WHERE Id = :opp.Id];

        System.assertEquals(expected, result.Good_Payer_Discount__c);
    }

    @isTest static void testNewOpp_Average() {
        // arrange
        Double expected = [SELECT Discount__c FROM Payor_History_Discounts__mdt WHERE DeveloperName = 'Default'].Discount__c;

        Account a = new Account (
            Name = 'testacct',
            Payor_History__c = 'Average'
        );
        insert a;

        Opportunity opp = new Opportunity (
            StageName = 'New',
            AccountId = a.Id,
            CloseDate = Date.today(),
            Name = 'testopp'
        );

        // act
        insert opp;

        // assert
        Opportunity result = [SELECT Good_Payer_Discount__c FROM Opportunity WHERE Id = :opp.Id];

        System.assertEquals(expected, result.Good_Payer_Discount__c);
    }

    @isTest static void testNewOpp_DefaultToExcellent() {
        // arrange
        Double expected = [SELECT Discount__c FROM Payor_History_Discounts__mdt WHERE DeveloperName = 'Excellent'].Discount__c;

        Account a = new Account (
            Name = 'testacct',
            Payor_History__c = 'Good'
        );
        insert a;

        Opportunity opp = new Opportunity (
            StageName = 'New',
            AccountId = a.Id,
            CloseDate = Date.today(),
            Name = 'testopp'
        );
        insert opp;

        // act
        a.Payor_History__c = 'Excellent';
        update a;

        // assert
        Opportunity result = [SELECT Good_Payer_Discount__c FROM Opportunity WHERE Id = :opp.Id];

        System.assertEquals(expected, result.Good_Payer_Discount__c);
    }

    @isTest static void testNewOpp_ExcellentToDefault() {
        // arrange
        Double expected = [SELECT Discount__c FROM Payor_History_Discounts__mdt WHERE DeveloperName = 'Default'].Discount__c;

        Account a = new Account (
            Name = 'testacct',
            Payor_History__c = 'Excellent'
        );
        insert a;

        Opportunity opp = new Opportunity (
            StageName = 'New',
            AccountId = a.Id,
            CloseDate = Date.today(),
            Name = 'testopp'
        );
        insert opp;

        // act
        a.Payor_History__c = 'Average';
        update a;

        // assert
        Opportunity result = [SELECT Good_Payer_Discount__c FROM Opportunity WHERE Id = :opp.Id];

        System.assertEquals(expected, result.Good_Payer_Discount__c);
    }

    // etc... need to test the IsClosed = false filter on the update process
}